HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

export ZSH=/Users/bill/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Set pure theme
ZSH_THEME=""
autoload -U promptinit; promptinit
autoload -U history-search-end
prompt pure
# set aliases
source ~/.aliases

# fuzzy matching
CASE_SENSITIVE="false"

# enable zsh syntax highlighting and autosuggestions
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# add zsh funtions path
fpath=(/usr/local/Homebrew/completions/zsh/ $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)
# Add homebrew python to the path
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"

# define plugins
plugins=(git colored-man colorize pip python brew osx zsh-autosuggestions zsh-syntax-highlighting history-substring-search)

# bind key for history search
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
